### PR TITLE
Wrong opcode "Construction.Unknown"

### PR DESCRIPTION
**Pull request by sofresh007**
From what i can see we have wrong opcode for this unknown packet and we had 2x 400 packets and the unknown packet supposed to have opcode x500

### CODE REVIEW

**Comment by QuentinGruber** [comment]
> From what i can see we have wrong opcode for this unknown packet and we had 2x 400 packets and the unknown packet supposed to have opcode x500

Hey, i'm very happy to see you contributing :) Could you prove what you are saying? For example the address where you found this information?

**Comment by Z1Meme** [comment]
> > From what i can see we have wrong opcode for this unknown packet and we had 2x 400 packets and the unknown packet supposed to have opcode x500
> 
> Hey, i'm very happy to see you contributing :) Could you prove what you are saying? For example the address where you found this information?

He is correct
`
switch ( *v6 )
      {
        case 2:
          HandlePlacementResponsePacket(a1, buffer, bufferSize_);
          break;
        case 4:
          HandlePlacementFinalizeResponse(a1, buffer, bufferSize_);
          break;
        case 5:
          HandleUnknownContructionPacket(a1, buffer, bufferSize_);
          break;
      }
`

**Review by Z1Meme — DISMISSED** [review]

**Review by Z1Meme — APPROVED** [review]

**Comment by Z1Meme** [comment]
@QuentinGruber not sure why "Labeler" is not successful, does it matter?

**Comment by QuentinGruber** [comment]
> @QuentinGruber not sure why "Labeler" is not successful, does it matter?

it's just an issue with chris not being a validated contributor, it will be fixed

**Pull request merged**
