### PR TITLE
hospital-lootables

### PR DESCRIPTION
**Pull request by Madman-gaming**

### CODE REVIEW

**Review by coderuk — DISMISSED** [review]

**Comment by QuentinGruber** [comment]
Hey @Madman-gaming thx for this PR can you fix the issues detected by our CI before we review this ? 😃

**Comment by Madman-gaming** [comment]
hopefully that fixed it

**Comment by Madman-gaming** [comment]
hopefully its fixed now an unfortunate copy and paste issue lol

**Comment by QuentinGruber** [comment]
still not @Madman-gaming try to run `npm i` and `npm test` on your side to debug this behavior

**Comment by Madman-gaming** [comment]
hopefully that works now ran check on my end

**Comment by Madman-gaming** [comment]
okay lets try again sorry still learning lol

**Comment by Madman-gaming** [comment]
hoping its fixed

**Comment by Madman-gaming** [comment]
what do i need to do to fix the last 2

**Comment by QuentinGruber** [comment]
> hoping its fixed

it seems but now there is conflicts 😭

**Comment by Madman-gaming** [comment]
yea not sure how to fix those avcio said he was gonna look at it but dont know if he did

**Comment by Madman-gaming** [comment]
> > hoping its fixed
> 
> it seems but now there is conflicts 😭

unsure how to fix

**Comment by Madman-gaming** [comment]
> > hoping its fixed
> 
> it seems but now there is conflicts 😭

how do i fix labeler

**Review by avcio9 — APPROVED** [review]

**Review by avcio9 — DISMISSED** [review]

**Review by avcio9 — APPROVED** [review]

**Pull request merged**
