### PR TITLE
Reversed packets and added /dev hideme

### PR DESCRIPTION
**Pull request by thegrreat1**
✖️ Features in this update ✖️
----------------------------------------------------------------------------------------------------------------------------------------
- Player will now bleed when taking 40% damage in one hit or health is less than 20% and taking any damage.
  Could change the value if wanted!
- Added /hax bandage. Will increase health slowly and stop bleeding when health is above 20%.

- Added /dev hideme "So @QuentinGruber  can hide himself from all the fans on live server 🤪 ".
- Decrease stamina if character is bleeding and running. And disable it from increasing while character is bleeding.

- Interactable burlapbag now spawns ontop of player on death
- --------------------------------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by thegrreat1** [comment]
*NOTICE TO MYSELF* Players zoning in after character has done /dev hidden can still see the hidden player.. Need to add a check for that.

**Comment by thegrreat1** [comment]
> 

Solved!

**Comment by thegrreat1** [comment]
> _NOTICE TO MYSELF_ Players zoning in after character has done /dev hideme can still see the hidden player.. Need to add a check for that. "Dunno how to do it yet tho 'sadface'"..

Solved!

**Comment by thegrreat1** [comment]
Should we add the chance of bleeding when taking 40% damage or should i delete it? You decide @QuentinGruber :)

Bleeding can be stopped by using /hax bandage.

**Comment by QuentinGruber** [comment]
> Should we add the chance of bleeding when taking 40%+ damage or should i delete it? You decide @QuentinGruber :)
> 
> Bleeding can be stopped by using /hax bandage.

I think it's a good idea 😛

**Comment by thegrreat1** [comment]
Everything seems to be working so im done with this one :octocat:

**Comment by thegrreat1** [comment]
Sorry for the spaghetti code... Everything seems to be working fine now :)

**Review by QuentinGruber — APPROVED** [review]

**Pull request merged**
