### PR TITLE
Optimization/LessFloodAtCharacterLogin

### PR DESCRIPTION
**Pull request by QuentinGruber**

### CODE REVIEW

**Comment by QuentinGruber** [comment]
Hey @Z1Meme , could you take a quick look at it if I haven't removed the sending of an essential packet that I don't know about?

**Comment by Z1Meme** [comment]
> Hey @Z1Meme , could you take a quick look at it if I haven't removed the sending of an essential packet that I don't know about?

ItemDefinitions and WeaponDefinitions absolutely need to be sent before sendself, this is updated on the weapons branch and weapons aren't constructed properly (They get constructed as a ClientItem instead of ClientWeapon) if you don't send both before sendself.

**Comment by QuentinGruber** [comment]
> > Hey @Z1Meme , could you take a quick look at it if I haven't removed the sending of an essential packet that I don't know about?
> 
> ItemDefinitions and WeaponDefinitions absolutely need to be sent before sendself, this is updated on the weapons branch and weapons aren't constructed properly (They get constructed as a ClientItem instead of ClientWeapon) if you don't send both before sendself.

Oh ok 😞 , i'm happy that i've asked you then aha btw you should open a draft PR for weapons i didn't knew you were working on the weapons branch.

**Comment by Z1Meme** [comment]
> > > Hey @Z1Meme , could you take a quick look at it if I haven't removed the sending of an essential packet that I don't know about?
> > 
> > ItemDefinitions and WeaponDefinitions absolutely need to be sent before sendself, this is updated on the weapons branch and weapons aren't constructed properly (They get constructed as a ClientItem instead of ClientWeapon) if you don't send both before sendself.
> 
> Oh ok 😞 , i'm happy that i've asked you then aha btw you should open a draft PR for weapons i didn't knew you were working on the weapons branch.

I just made the pull request, I thought I already had one.

**Comment by QuentinGruber** [comment]
weird after moving the itemsDef and WeapDef before sendself the player can't really move ( like when we firstly spawn a character back in 2015 ) Had you add some others stuff on your branch? Since it didn't have the issue and i don't find things that should produce that 😕

**Comment by Z1Meme** [comment]
Weapons only get constructed correctly when you put those packets before sendself, which makes it so the read function for the weapon item gets longer, so if you don't have the updated pack function it breaks sendself causing stats to not be parsed (sprint speed etc).

**Comment by Z1Meme** [comment]
Sorry for the late reply, I have been very busy.

**Pull request merged**
