### PR TITLE
Scubs fix added adr and hogmask adr

### PR DESCRIPTION
**Pull request by Zam6969**
Pull This branch for more models :) so we can work on more skins to get them working

### CODE REVIEW

**Review by Zam6969 — COMMENTED** [review]
rem pak-lock.json

**Comment by QuentinGruber** [comment]
> rem pak-lock.json

well you should not remove it 😄 revert this commit pls

**Comment by xZammu** [comment]
> > rem pak-lock.json
> 
> well you should not remove it 😄 revert this commit pls

Ill try to im new to this haha

**Comment by xZammu** [comment]
Did i do it right? Lmao

**Comment by QuentinGruber** [comment]
> Did i do it right? Lmao

Not really this Pr still change stuff on package-lock.json use git commands to revert them 😄

**Comment by xZammu** [comment]
Just delete this ill do it again lmao

**Comment by xZammu** [comment]
Im so confused lmao im gunna watch some yt to figure this out haha

**Pull request closed without merging**
