### PR TITLE
buh

### PR DESCRIPTION
**Pull request by Zam6969**
adding more  tho

### CODE REVIEW

**Comment by Zam6969** [comment]
how can i target self if only /kit pvp is typed

**Comment by Zam6969** [comment]
Got it nvm

**Comment by Zam6969** [comment]
done pull branch whenever

**Comment by Zam6969** [comment]
basically it will get where ur corsair is at and teleport u there

**Comment by Zam6969** [comment]
but help

**Review by QuentinGruber — DISMISSED** [review]
/tpl always tp me under the map and /kit doesn't work, probably bc there is a duplicate

**Comment by Zam6969** [comment]
@QuentinGruber i need help with the tpl command and the kit command should work now

**Comment by Zam6969** [comment]
doesnt work correctly cant figure it out
i tried this 

  {
    name: "tttt",
    permissionLevel: PermissionLevels.ADMIN,
    execute: (server, client, packetData: any) => {
      server.sendData(client, "ClientUpdate.UpdateLocation", {
        position: packetData.position,
      });
    },
  },
  
  doesnt work also

**Comment by Zam6969** [comment]
@QuentinGruber  can you help me with the tpl command i cant figure it out.

**Comment by Zam6969** [comment]
so gkit works but doesnt give it to urself if u type gkit pvp you would have to type gkit pvp zammu

**Comment by Z1Meme** [comment]
Removed /gkit since there's really no reason an admin would give a normal player the pvp/build/parts/skins kit unless on a modded server, in which case they could add that command themselves. Also removed /tpl since it can't work without a serversided heightmap, which is not added yet. Would be better to do this with a special admin gun that TPs the player to the hitLocation of the projectile.

**Review by Z1Meme — APPROVED** [review]

**Review by Z1Meme — APPROVED** [review]

**Pull request merged**
