### PR TITLE
Bandaid vehicle fairplay fix

### PR DESCRIPTION
**Pull request by Nikolassparrow**
Fairplay kicking in vehicles has something to do with the way time works in the distance equation inside of checkVehicleSpeed (fairplaymanager)

This is just a bandaid fix until a more permanent one can be found.

### CODE REVIEW

**Review by QuentinGruber — COMMENTED** [review]
Idk what @avcio9 think of this if you want maybe it's better to disable this until we fix it

**Comment by avcio9** [comment]
Are we using a main or dev branch on main servers? the fix i made a few days ago is on dev but not merged into main branch

**Comment by avcio9** [comment]
Looks like i've found the issue, it was hard to catch on local server cause of low ping

**Comment by QuentinGruber** [comment]
> Are we using a main or dev branch on main servers? the fix i made a few days ago is on dev but not merged into main branch

We use the latest dev i will push a regular version today

**Comment by QuentinGruber** [comment]
> Looks like i've found the issue, it was hard to catch on local server cause of low ping

Make sense gj!

**Review by QuentinGruber — APPROVED** [review]

**Pull request merged**
